# Generated by Django 2.1.4 on 2018-12-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvedora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField(default=0)),
                ('quant_estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publicadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicadoras', to='games.Jogo')),
            ],
        ),
        migrations.AddField(
            model_name='desenvolvedora',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desenvolvedoras', to='games.Jogo'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='jogos_carrinho',
            field=models.ManyToManyField(to='games.Jogo'),
        ),
    ]
