# Generated by Django 2.1.4 on 2018-12-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao_jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Publicadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='publicacao_jogo',
            name='publicadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Publicadora'),
        ),
        migrations.AddField(
            model_name='avaliacao_jogo',
            name='avaliadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Avaliadora'),
        ),
        migrations.AddField(
            model_name='avaliacao_jogo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Jogo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='avaliacao',
            field=models.ManyToManyField(through='games.Avaliacao_jogo', to='games.Avaliadora'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='publicadoras',
            field=models.ManyToManyField(through='games.Publicacao_jogo', to='games.Publicadora'),
        ),
    ]
