# Generated by Django 2.1.4 on 2018-12-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20181210_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao_jogo',
            name='avaliadora',
        ),
        migrations.RemoveField(
            model_name='avaliacao_jogo',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='avaliacao',
        ),
        migrations.DeleteModel(
            name='Avaliacao_jogo',
        ),
        migrations.DeleteModel(
            name='Avaliadora',
        ),
    ]
