# Generated by Django 2.1.4 on 2018-12-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20181210_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='games.Jogo')),
            ],
        ),
    ]
